version: '3.8'

services:
  microservice:
    build:
      context: ./microservice
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - microservice

  frontend_admin:
    build:
      context: ./frontend_admin
      dockerfile: ./Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - microservice


  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432" 

volumes:
  postgres_data:

